services:
  postgres:
    container_name: shared-todo
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - shared-todo-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Map TCP port 5433 on the host to 5432 in the container

volumes:
  shared-todo-pgdata:
    driver: local
